# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.vm.hostname = "ZFS"  
  config.vm.network "public_network", ip: "192.168.1.100"
  config.vm.define "testing"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
  end
end
